# Generated by Django 5.1 on 2024-08-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255)),
                ('request_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='processing', max_length=55)),
                ('performed_at', models.CharField(max_length=255, null=True)),
                ('canceled_at', models.CharField(max_length=255, null=True)),
                ('created_at', models.CharField(max_length=255, null=True)),
                ('reason', models.IntegerField(null=True)),
                ('account_id', models.CharField(max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Payme transaction',
                'verbose_name_plural': 'Payme transactions',
            },
        ),
    ]
