GKLAS = {
    11: "Bâtiments d'habitation",
    111: "Bâtiments d'habitation",
    1110: "Maisons à un logement",
    112: "Immeubles collectifs",
    1121: "Maisons à deux logements",
    1122: "Immeubles à trois logements et plus",
    113: "Habitat communautaire",
    1130: "Habitat communautaire",
    12: "Bâtiments non résidentiels",
    121: "Hôtels et bâtiments d'hébergement",
    1211: "Hôtels",
    1212: "Autres bâtiments d'hébergement de tourisme",
    122: "Immeubles de bureaux",
    1220: "Immeubles de bureaux",
    123: "Bâtiments commerciaux",
    1230: "Bâtiments commerciaux",
    1231: "Restaurants et bars dans des bâtiments sans usage résidentiel",
    124: "Bâtiments pour les transports et les communications",
    1241: "Gares, aérogares, centraux téléphoniques",
    1242: "Garages",
    125: "Bâtiments industriels et entrepôts",
    1251: "Bâtiments industriels",
    1252: "Réservoirs, silos et entrepôts",
    126: "Bâtiments à usage culturel, récréatif, éducatif ou sanitaire",
    1261: "Bâtiments à usage culturel, récréatif, éducatif ou sanitaire",
    1262: "Musées et bibliothèques",
    1263: "Bâtiments pour l'enseignement et la recherche",
    1264: "Hôpitaux et établissements de santé",
    1265: "Salles de sport",
    127: "Autres bâtiments non résidentiels",
    1271: "Bâtiment d'exploitation agricole (remplacé par les 1276, 1277 et 1278)",
    1272: "Edifices culturels et religieux",
    1273: "Monuments historiques ou classés",
    1274: "Autres bâtiments non classés ailleurs",
    1275: "Autres bâtiments pour l'hébergement collectif",
    1276: "Bâtiments pour la garde d'animaux",
    1277: "Bâtiments pour les cultures végétales",
    1278: "Autres bâtiments d'exploitation agricole",
}
