PTYPAG = {
    6101: "CFF (Chemins de fer fédéraux)",
    6103: "DDPS (Département fédéral de la défense, de la protection de la population et des sports)",
    6104: "OFCL (Office fédéral des constructions et de la logistique)",
    6105: "OFROU (Office fédéral des routes)",
    6107: "Swisscom",
    6108: "La Poste",
    6110: "Cantons (sans leurs entreprises de droit public)",
    6111: "Entreprises de droit public d'un canton (sans les banques cantonales et les assurances incendie)",
    6115: "Communes y compris leurs corporations de droit public (bourgeoisie, corporations agricoles etc.), mais sans leurs entreprises de droit public",
    6116: "Entreprises de droit public de la commune (transports publics, services industriels, gaz, eau, électricité etc.)",
    6121: "Sociétés d'assurance sans les caisses de pension et les caisses maladie",
    6122: "Institutions de prévoyance (caisses de pension)",
    6123: "Caisses maladie, CNA",
    6124: "Banques (Banque nationale, grandes banques, banques cantonales, banques régionales, caisses d'épargne, banques privées), fonds immobiliers ou holdings financières",
    6131: "Usines d'électricité privées",
    6132: "Usines à gaz privées",
    6133: "Chemins de fer privés",
    6141: "Sociétés individuelles ou de personnes (simples, collectives ou en commandite) de la branche immobilière",
    6142: "Coopératives de logement, dont les membres occuperont la majorité des logements du bâtiment",
    6143: "Sociétés de capitaux (SA, coopératives, SA en commandite, Sàrl) de la branche immobilière",
    6161: "Particuliers, y compris hoiries",
    6151: "Sociétés individuelles ou de personnes (simples, collectives ou en commandite) sans la branche immobilière",
    6152: "Sociétés de capitaux (SA, coopératives, SA en commandite, Sàrl) sans la branche immobilière",
    6162: "Autres investisseurs privés (églises, églises officielles incluses, fondations qui ne sont pas des caisses de pension, associations etc.)",
    6163: "Organisations internationales, ambassades",
}
