
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-03T19:08:29+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c68993bac83d18afa5768835fbfc13a376dcb0fd",
 "version": "1.9.12.post0.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
