import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_f7d49dbd8b(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_a981fa950f():spartaqube_cli.list()
@app.command()
def sparta_66d923321c():spartaqube_cli.sparta_66d923321c()
@app.command()
def sparta_31f0b4a627():print('Hello world!')
if __name__=='__main__':app()