# Generated by Django 3.2.13 on 2022-05-29 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kort', '0011_cardprinter_card_detector'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlayout',
            name='height',
            field=models.PositiveIntegerField(default=1, verbose_name='Height'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardlayout',
            name='width',
            field=models.PositiveIntegerField(default=1, verbose_name='Width'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardprintjob',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='kort.card', verbose_name='Card'),
        ),
        migrations.CreateModel(
            name='CardLayoutMediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_data', models.JSONField(default=dict, editable=False)),
                ('media_file', models.FileField(upload_to='card_layouts/media/', verbose_name='Media file')),
                ('card_layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='kort.cardlayout', verbose_name='Card layout')),
            ],
            options={
                'verbose_name': 'Media file for a card layout',
                'verbose_name_plural': 'Media files for card layouts',
            },
            managers=[
            ],
        ),
    ]
