from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.AUBO_i3 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.AUBO_i5 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.AUBO_i7 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.AUBO_i10 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.AUBO_i12 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.AUBO_i16 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.AUBO_i20 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.AUCTECH_X3_618 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.AUCTECH_X5_910 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.AUCTECH_X7_910 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.AUCTECH_X10_1300 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.AUCTECH_X12_1300 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.AUCTECH_X16_960 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.AUCTECH_X16_2000 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.AUCTECH_X20_1400 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.AUCTECH_X25_1800 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.AUCTECH_X30_1100 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.cpcRobot_S0 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Dobot_CR3 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Dobot_CR3A import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Dobot_CR3L import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Dobot_CR5 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Dobot_CR5A import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Dobot_CR7 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Dobot_CR7A import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Dobot_CR10 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Dobot_CR10A import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Dobot_CR12 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Dobot_CR12A import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Dobot_CR16 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Dobot_CR16A import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Dobot_CR20A import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Dobot_Magician_E6 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Dobot_Nova2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Dobot_Nova5 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Efort_GR680 import * # doesn't work because of "wild" theta values
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Elephant_Robotics_myCobot_320 import * # Not available on roboDK library
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Elephant_Robotics_myCobot_Pro600 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Elite_Robots_CS63 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Elite_Robots_CS66 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Elite_Robots_CS612 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Elite_Robots_CS620 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Elite_Robots_CS625 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Elite_Robots_EC63 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Elite_Robots_EC64_19 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Elite_Robots_EC66 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Elite_Robots_EC612 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Elite_Robots_EC616 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.FAIR_Innovation_F16 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.FAIR_Innovation_FR3 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.FAIR_Innovation_FR5 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.FAIR_Innovation_FR10 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.FAIR_Innovation_FR20 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Hans_S20_1700 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Hans_S30_1800 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Hanwha_HCR3 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Hanwha_HCR5 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.IIMT_CA_05 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.IIMT_CR_03 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.IIMT_CR_10 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.IIMT_CR_16 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.JAKA_Pro_16 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.JAKA_Zu3 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.JAKA_Zu5 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.JAKA_Zu7 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.JAKA_Zu12 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.JAKA_Zu18 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.JAKA_Zu20 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Omron_TM5_700 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Omron_TM5_900 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Omron_TM5X_700 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Omron_TM5X_900 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Omron_TM12 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Omron_TM12X import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Omron_TM14 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Omron_TM14X import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.RB3_1200 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.RB5_850 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.RB5_850A import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.RB10_1300 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.RoboDK_RDK_COBOT_1200 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Schneider_Electric_LXMRL03S0000 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Schneider_Electric_LXMRL05S0000 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Schneider_Electric_LXMRL07S0000 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Schneider_Electric_LXMRL12S0000 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Schneider_Electric_LXMRL18S0000 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Siasun_GCR5_910 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Siasun_GCR10_1300 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Siasun_GCR14_1400 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Siasun_GCR20_1100 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Standard_Bots_RO1 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.TM5_700 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.TM5_900 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.TM5S import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.TM5SX import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.TM5X_700 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.TM5X_900 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.TM7S import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.TM7SX import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.TM12 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.TM12S import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.TM12SX import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.TM12X import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.TM14 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.TM14S import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.TM14SX import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.TM14X import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.TM16 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.TM16X import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.TM20 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.TM20X import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.Toney_M10 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.UR3 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.UR3e import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.UR5 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.UR5e import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.UR10 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.UR10e import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.UR16e import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.UR20 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__collaborativeRobots.UR30 import *