from robotkinematicscatalogue.inversekinematics.__5DOF.Fanuc_LR_Mate100iB import *
from robotkinematicscatalogue.inversekinematics.__5DOF.Fanuc_LR_Mate_200iC_5H import *
from robotkinematicscatalogue.inversekinematics.__5DOF.Fanuc_M_410iB_140H import *
from robotkinematicscatalogue.inversekinematics.__5DOF.KUKA_youBot import *
from robotkinematicscatalogue.inversekinematics.__5DOF.Motoman_MPL80 import *
from robotkinematicscatalogue.inversekinematics.__5DOF.Kawasaki_RD80N import *
from robotkinematicscatalogue.inversekinematics.__5DOF.KUKA_KR1000_L950_titan_PA import *
from robotkinematicscatalogue.inversekinematics.__5DOF.KUKA_KR1000_L1300_titan_PA import *
from robotkinematicscatalogue.inversekinematics.__5DOF.Mitsubishi_RV_2AJ import *
from robotkinematicscatalogue.inversekinematics.__5DOF.Nachi_MC500P import *
from robotkinematicscatalogue.inversekinematics.__5DOF.Staubli_RX170HSM import *
from robotkinematicscatalogue.inversekinematics.__5DOF.uFactory_xArm5 import *