# Generated by Django 5.1 on 2024-08-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='account_id',
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='account',
            field=models.JSONField(null=True),
        ),
    ]
