_PREFIX = "DOTTOOLS"

HOST_NAME_ENV = f"{_PREFIX}_HOST_NAME"
CONFIG_FILE_PATH_ENV_VAR = f"{_PREFIX}_CFG_PATH"

ROOT_PATH_ENV_VAR = f"{_PREFIX}_ROOT_PATH"
BASHRCD_PATH_ENV = f"{_PREFIX}_BASHRCD_PATH"
SCRIPTS_PATH_ENV = f"{_PREFIX}_SCRIPTS_PATH"
PROMPT_ENV_VAR = f"{_PREFIX}_PROMPT"
