
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-30T17:08:01-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "657e3dd927915890d67e5d25c3c1567ebe8bc0bd",
 "version": "2.44.0rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
