
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-09T21:01:06+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d8a4d37c3451a04656eefdc07f227faeab35436e",
 "version": "2.7.15.post0.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
