
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-30T12:37:52+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "55687211a6c1331ea53419af801adb70bb9df68a",
 "version": "2.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
