# coding: utf-8

"""
    OnePlan API

    This is an automatically generated OpenAPI specification for the OnePlan API based on the api help docs.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AllocationClass(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'start': 'date',
        'end': 'date',
        'hours_per_month': 'DecimalNumber',
        'allocation_percent': 'DecimalNumber',
        'total_hours': 'DecimalNumber'
    }

    attribute_map = {
        'start': 'Start',
        'end': 'End',
        'hours_per_month': 'HoursPerMonth',
        'allocation_percent': 'AllocationPercent',
        'total_hours': 'TotalHours'
    }

    def __init__(self, start=None, end=None, hours_per_month=None, allocation_percent=None, total_hours=None):  # noqa: E501
        """AllocationClass - a model defined in Swagger"""  # noqa: E501
        self._start = None
        self._end = None
        self._hours_per_month = None
        self._allocation_percent = None
        self._total_hours = None
        self.discriminator = None
        if start is not None:
            self.start = start
        if end is not None:
            self.end = end
        if hours_per_month is not None:
            self.hours_per_month = hours_per_month
        if allocation_percent is not None:
            self.allocation_percent = allocation_percent
        if total_hours is not None:
            self.total_hours = total_hours

    @property
    def start(self):
        """Gets the start of this AllocationClass.  # noqa: E501


        :return: The start of this AllocationClass.  # noqa: E501
        :rtype: date
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this AllocationClass.


        :param start: The start of this AllocationClass.  # noqa: E501
        :type: date
        """

        self._start = start

    @property
    def end(self):
        """Gets the end of this AllocationClass.  # noqa: E501


        :return: The end of this AllocationClass.  # noqa: E501
        :rtype: date
        """
        return self._end

    @end.setter
    def end(self, end):
        """Sets the end of this AllocationClass.


        :param end: The end of this AllocationClass.  # noqa: E501
        :type: date
        """

        self._end = end

    @property
    def hours_per_month(self):
        """Gets the hours_per_month of this AllocationClass.  # noqa: E501


        :return: The hours_per_month of this AllocationClass.  # noqa: E501
        :rtype: DecimalNumber
        """
        return self._hours_per_month

    @hours_per_month.setter
    def hours_per_month(self, hours_per_month):
        """Sets the hours_per_month of this AllocationClass.


        :param hours_per_month: The hours_per_month of this AllocationClass.  # noqa: E501
        :type: DecimalNumber
        """

        self._hours_per_month = hours_per_month

    @property
    def allocation_percent(self):
        """Gets the allocation_percent of this AllocationClass.  # noqa: E501


        :return: The allocation_percent of this AllocationClass.  # noqa: E501
        :rtype: DecimalNumber
        """
        return self._allocation_percent

    @allocation_percent.setter
    def allocation_percent(self, allocation_percent):
        """Sets the allocation_percent of this AllocationClass.


        :param allocation_percent: The allocation_percent of this AllocationClass.  # noqa: E501
        :type: DecimalNumber
        """

        self._allocation_percent = allocation_percent

    @property
    def total_hours(self):
        """Gets the total_hours of this AllocationClass.  # noqa: E501


        :return: The total_hours of this AllocationClass.  # noqa: E501
        :rtype: DecimalNumber
        """
        return self._total_hours

    @total_hours.setter
    def total_hours(self, total_hours):
        """Sets the total_hours of this AllocationClass.


        :param total_hours: The total_hours of this AllocationClass.  # noqa: E501
        :type: DecimalNumber
        """

        self._total_hours = total_hours

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AllocationClass, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AllocationClass):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
