# coding: utf-8

"""
    OnePlan API

    This is an automatically generated OpenAPI specification for the OnePlan API based on the api help docs.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BubbleChartSettings(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'x_field': 'GloballyUniqueIdentifier',
        'y_field': 'GloballyUniqueIdentifier',
        'size_field': 'GloballyUniqueIdentifier'
    }

    attribute_map = {
        'x_field': 'xField',
        'y_field': 'yField',
        'size_field': 'sizeField'
    }

    def __init__(self, x_field=None, y_field=None, size_field=None):  # noqa: E501
        """BubbleChartSettings - a model defined in Swagger"""  # noqa: E501
        self._x_field = None
        self._y_field = None
        self._size_field = None
        self.discriminator = None
        if x_field is not None:
            self.x_field = x_field
        if y_field is not None:
            self.y_field = y_field
        if size_field is not None:
            self.size_field = size_field

    @property
    def x_field(self):
        """Gets the x_field of this BubbleChartSettings.  # noqa: E501


        :return: The x_field of this BubbleChartSettings.  # noqa: E501
        :rtype: GloballyUniqueIdentifier
        """
        return self._x_field

    @x_field.setter
    def x_field(self, x_field):
        """Sets the x_field of this BubbleChartSettings.


        :param x_field: The x_field of this BubbleChartSettings.  # noqa: E501
        :type: GloballyUniqueIdentifier
        """

        self._x_field = x_field

    @property
    def y_field(self):
        """Gets the y_field of this BubbleChartSettings.  # noqa: E501


        :return: The y_field of this BubbleChartSettings.  # noqa: E501
        :rtype: GloballyUniqueIdentifier
        """
        return self._y_field

    @y_field.setter
    def y_field(self, y_field):
        """Sets the y_field of this BubbleChartSettings.


        :param y_field: The y_field of this BubbleChartSettings.  # noqa: E501
        :type: GloballyUniqueIdentifier
        """

        self._y_field = y_field

    @property
    def size_field(self):
        """Gets the size_field of this BubbleChartSettings.  # noqa: E501


        :return: The size_field of this BubbleChartSettings.  # noqa: E501
        :rtype: GloballyUniqueIdentifier
        """
        return self._size_field

    @size_field.setter
    def size_field(self, size_field):
        """Sets the size_field of this BubbleChartSettings.


        :param size_field: The size_field of this BubbleChartSettings.  # noqa: E501
        :type: GloballyUniqueIdentifier
        """

        self._size_field = size_field

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BubbleChartSettings, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BubbleChartSettings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
