# coding: utf-8

"""
    OnePlan API

    This is an automatically generated OpenAPI specification for the OnePlan API based on the api help docs.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GanttSyncResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tasks': 'Object',
        'assignments': 'Object',
        'dependencies': 'Object',
        'resources': 'Object',
        'process': 'AsyncProcessResult',
        'revision': 'int',
        'need_refresh': 'bool',
        'success': 'bool',
        'message': 'str',
        'request_id': 'UnsignedInteger'
    }

    attribute_map = {
        'tasks': 'tasks',
        'assignments': 'assignments',
        'dependencies': 'dependencies',
        'resources': 'resources',
        'process': 'Process',
        'revision': 'revision',
        'need_refresh': 'NeedRefresh',
        'success': 'success',
        'message': 'Message',
        'request_id': 'requestId'
    }

    def __init__(self, tasks=None, assignments=None, dependencies=None, resources=None, process=None, revision=None, need_refresh=None, success=None, message=None, request_id=None):  # noqa: E501
        """GanttSyncResponse - a model defined in Swagger"""  # noqa: E501
        self._tasks = None
        self._assignments = None
        self._dependencies = None
        self._resources = None
        self._process = None
        self._revision = None
        self._need_refresh = None
        self._success = None
        self._message = None
        self._request_id = None
        self.discriminator = None
        if tasks is not None:
            self.tasks = tasks
        if assignments is not None:
            self.assignments = assignments
        if dependencies is not None:
            self.dependencies = dependencies
        if resources is not None:
            self.resources = resources
        if process is not None:
            self.process = process
        if revision is not None:
            self.revision = revision
        if need_refresh is not None:
            self.need_refresh = need_refresh
        if success is not None:
            self.success = success
        if message is not None:
            self.message = message
        if request_id is not None:
            self.request_id = request_id

    @property
    def tasks(self):
        """Gets the tasks of this GanttSyncResponse.  # noqa: E501


        :return: The tasks of this GanttSyncResponse.  # noqa: E501
        :rtype: Object
        """
        return self._tasks

    @tasks.setter
    def tasks(self, tasks):
        """Sets the tasks of this GanttSyncResponse.


        :param tasks: The tasks of this GanttSyncResponse.  # noqa: E501
        :type: Object
        """

        self._tasks = tasks

    @property
    def assignments(self):
        """Gets the assignments of this GanttSyncResponse.  # noqa: E501


        :return: The assignments of this GanttSyncResponse.  # noqa: E501
        :rtype: Object
        """
        return self._assignments

    @assignments.setter
    def assignments(self, assignments):
        """Sets the assignments of this GanttSyncResponse.


        :param assignments: The assignments of this GanttSyncResponse.  # noqa: E501
        :type: Object
        """

        self._assignments = assignments

    @property
    def dependencies(self):
        """Gets the dependencies of this GanttSyncResponse.  # noqa: E501


        :return: The dependencies of this GanttSyncResponse.  # noqa: E501
        :rtype: Object
        """
        return self._dependencies

    @dependencies.setter
    def dependencies(self, dependencies):
        """Sets the dependencies of this GanttSyncResponse.


        :param dependencies: The dependencies of this GanttSyncResponse.  # noqa: E501
        :type: Object
        """

        self._dependencies = dependencies

    @property
    def resources(self):
        """Gets the resources of this GanttSyncResponse.  # noqa: E501


        :return: The resources of this GanttSyncResponse.  # noqa: E501
        :rtype: Object
        """
        return self._resources

    @resources.setter
    def resources(self, resources):
        """Sets the resources of this GanttSyncResponse.


        :param resources: The resources of this GanttSyncResponse.  # noqa: E501
        :type: Object
        """

        self._resources = resources

    @property
    def process(self):
        """Gets the process of this GanttSyncResponse.  # noqa: E501


        :return: The process of this GanttSyncResponse.  # noqa: E501
        :rtype: AsyncProcessResult
        """
        return self._process

    @process.setter
    def process(self, process):
        """Sets the process of this GanttSyncResponse.


        :param process: The process of this GanttSyncResponse.  # noqa: E501
        :type: AsyncProcessResult
        """

        self._process = process

    @property
    def revision(self):
        """Gets the revision of this GanttSyncResponse.  # noqa: E501


        :return: The revision of this GanttSyncResponse.  # noqa: E501
        :rtype: int
        """
        return self._revision

    @revision.setter
    def revision(self, revision):
        """Sets the revision of this GanttSyncResponse.


        :param revision: The revision of this GanttSyncResponse.  # noqa: E501
        :type: int
        """

        self._revision = revision

    @property
    def need_refresh(self):
        """Gets the need_refresh of this GanttSyncResponse.  # noqa: E501


        :return: The need_refresh of this GanttSyncResponse.  # noqa: E501
        :rtype: bool
        """
        return self._need_refresh

    @need_refresh.setter
    def need_refresh(self, need_refresh):
        """Sets the need_refresh of this GanttSyncResponse.


        :param need_refresh: The need_refresh of this GanttSyncResponse.  # noqa: E501
        :type: bool
        """

        self._need_refresh = need_refresh

    @property
    def success(self):
        """Gets the success of this GanttSyncResponse.  # noqa: E501


        :return: The success of this GanttSyncResponse.  # noqa: E501
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success):
        """Sets the success of this GanttSyncResponse.


        :param success: The success of this GanttSyncResponse.  # noqa: E501
        :type: bool
        """

        self._success = success

    @property
    def message(self):
        """Gets the message of this GanttSyncResponse.  # noqa: E501


        :return: The message of this GanttSyncResponse.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this GanttSyncResponse.


        :param message: The message of this GanttSyncResponse.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def request_id(self):
        """Gets the request_id of this GanttSyncResponse.  # noqa: E501


        :return: The request_id of this GanttSyncResponse.  # noqa: E501
        :rtype: UnsignedInteger
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id):
        """Sets the request_id of this GanttSyncResponse.


        :param request_id: The request_id of this GanttSyncResponse.  # noqa: E501
        :type: UnsignedInteger
        """

        self._request_id = request_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GanttSyncResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GanttSyncResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
