# coding: utf-8

"""
    OnePlan API

    This is an automatically generated OpenAPI specification for the OnePlan API based on the api help docs.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TimesheetRowDate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_date': 'date',
        'notes': 'str',
        'hours': 'dict(str, DecimalNumber)',
        'fields': 'dict(str, Object)'
    }

    attribute_map = {
        '_date': 'Date',
        'notes': 'Notes',
        'hours': 'Hours',
        'fields': 'Fields'
    }

    def __init__(self, _date=None, notes=None, hours=None, fields=None):  # noqa: E501
        """TimesheetRowDate - a model defined in Swagger"""  # noqa: E501
        self.__date = None
        self._notes = None
        self._hours = None
        self._fields = None
        self.discriminator = None
        if _date is not None:
            self._date = _date
        if notes is not None:
            self.notes = notes
        if hours is not None:
            self.hours = hours
        if fields is not None:
            self.fields = fields

    @property
    def _date(self):
        """Gets the _date of this TimesheetRowDate.  # noqa: E501


        :return: The _date of this TimesheetRowDate.  # noqa: E501
        :rtype: date
        """
        return self.__date

    @_date.setter
    def _date(self, _date):
        """Sets the _date of this TimesheetRowDate.


        :param _date: The _date of this TimesheetRowDate.  # noqa: E501
        :type: date
        """

        self.__date = _date

    @property
    def notes(self):
        """Gets the notes of this TimesheetRowDate.  # noqa: E501


        :return: The notes of this TimesheetRowDate.  # noqa: E501
        :rtype: str
        """
        return self._notes

    @notes.setter
    def notes(self, notes):
        """Sets the notes of this TimesheetRowDate.


        :param notes: The notes of this TimesheetRowDate.  # noqa: E501
        :type: str
        """

        self._notes = notes

    @property
    def hours(self):
        """Gets the hours of this TimesheetRowDate.  # noqa: E501


        :return: The hours of this TimesheetRowDate.  # noqa: E501
        :rtype: dict(str, DecimalNumber)
        """
        return self._hours

    @hours.setter
    def hours(self, hours):
        """Sets the hours of this TimesheetRowDate.


        :param hours: The hours of this TimesheetRowDate.  # noqa: E501
        :type: dict(str, DecimalNumber)
        """

        self._hours = hours

    @property
    def fields(self):
        """Gets the fields of this TimesheetRowDate.  # noqa: E501


        :return: The fields of this TimesheetRowDate.  # noqa: E501
        :rtype: dict(str, Object)
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """Sets the fields of this TimesheetRowDate.


        :param fields: The fields of this TimesheetRowDate.  # noqa: E501
        :type: dict(str, Object)
        """

        self._fields = fields

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TimesheetRowDate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TimesheetRowDate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
