# coding: utf-8

"""
    OnePlan API

    This is an automatically generated OpenAPI specification for the OnePlan API based on the api help docs.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserAccess(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'upn': 'GloballyUniqueIdentifier',
        'level': 'AccessLevel',
        'inherited': 'bool',
        'access_type': 'AccessType'
    }

    attribute_map = {
        'upn': 'upn',
        'level': 'Level',
        'inherited': 'Inherited',
        'access_type': 'AccessType'
    }

    def __init__(self, upn=None, level=None, inherited=None, access_type=None):  # noqa: E501
        """UserAccess - a model defined in Swagger"""  # noqa: E501
        self._upn = None
        self._level = None
        self._inherited = None
        self._access_type = None
        self.discriminator = None
        if upn is not None:
            self.upn = upn
        if level is not None:
            self.level = level
        if inherited is not None:
            self.inherited = inherited
        if access_type is not None:
            self.access_type = access_type

    @property
    def upn(self):
        """Gets the upn of this UserAccess.  # noqa: E501


        :return: The upn of this UserAccess.  # noqa: E501
        :rtype: GloballyUniqueIdentifier
        """
        return self._upn

    @upn.setter
    def upn(self, upn):
        """Sets the upn of this UserAccess.


        :param upn: The upn of this UserAccess.  # noqa: E501
        :type: GloballyUniqueIdentifier
        """

        self._upn = upn

    @property
    def level(self):
        """Gets the level of this UserAccess.  # noqa: E501


        :return: The level of this UserAccess.  # noqa: E501
        :rtype: AccessLevel
        """
        return self._level

    @level.setter
    def level(self, level):
        """Sets the level of this UserAccess.


        :param level: The level of this UserAccess.  # noqa: E501
        :type: AccessLevel
        """

        self._level = level

    @property
    def inherited(self):
        """Gets the inherited of this UserAccess.  # noqa: E501


        :return: The inherited of this UserAccess.  # noqa: E501
        :rtype: bool
        """
        return self._inherited

    @inherited.setter
    def inherited(self, inherited):
        """Sets the inherited of this UserAccess.


        :param inherited: The inherited of this UserAccess.  # noqa: E501
        :type: bool
        """

        self._inherited = inherited

    @property
    def access_type(self):
        """Gets the access_type of this UserAccess.  # noqa: E501


        :return: The access_type of this UserAccess.  # noqa: E501
        :rtype: AccessType
        """
        return self._access_type

    @access_type.setter
    def access_type(self, access_type):
        """Sets the access_type of this UserAccess.


        :param access_type: The access_type of this UserAccess.  # noqa: E501
        :type: AccessType
        """

        self._access_type = access_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserAccess, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserAccess):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
