
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-29T15:47:29+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "284d9dc1b1c7208af675545541c0ef339a9299db",
 "version": "2.4.34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
