# Generated by Django 4.1.10 on 2024-08-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0009_example_classification"),
        ("data_export", "0004_exportedcomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportedClassification",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("examples.example",),
        ),
    ]
