# coding: utf-8

"""
    OnePlan API

    This is an automatically generated OpenAPI specification for the OnePlan API based on the api help docs.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FieldSnapshot(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_date': 'date',
        'status_report_id': 'GloballyUniqueIdentifier',
        'fields': 'dict(str, Object)'
    }

    attribute_map = {
        '_date': 'Date',
        'status_report_id': 'StatusReportId',
        'fields': 'Fields'
    }

    def __init__(self, _date=None, status_report_id=None, fields=None):  # noqa: E501
        """FieldSnapshot - a model defined in Swagger"""  # noqa: E501
        self.__date = None
        self._status_report_id = None
        self._fields = None
        self.discriminator = None
        if _date is not None:
            self._date = _date
        if status_report_id is not None:
            self.status_report_id = status_report_id
        if fields is not None:
            self.fields = fields

    @property
    def _date(self):
        """Gets the _date of this FieldSnapshot.  # noqa: E501


        :return: The _date of this FieldSnapshot.  # noqa: E501
        :rtype: date
        """
        return self.__date

    @_date.setter
    def _date(self, _date):
        """Sets the _date of this FieldSnapshot.


        :param _date: The _date of this FieldSnapshot.  # noqa: E501
        :type: date
        """

        self.__date = _date

    @property
    def status_report_id(self):
        """Gets the status_report_id of this FieldSnapshot.  # noqa: E501


        :return: The status_report_id of this FieldSnapshot.  # noqa: E501
        :rtype: GloballyUniqueIdentifier
        """
        return self._status_report_id

    @status_report_id.setter
    def status_report_id(self, status_report_id):
        """Sets the status_report_id of this FieldSnapshot.


        :param status_report_id: The status_report_id of this FieldSnapshot.  # noqa: E501
        :type: GloballyUniqueIdentifier
        """

        self._status_report_id = status_report_id

    @property
    def fields(self):
        """Gets the fields of this FieldSnapshot.  # noqa: E501


        :return: The fields of this FieldSnapshot.  # noqa: E501
        :rtype: dict(str, Object)
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """Sets the fields of this FieldSnapshot.


        :param fields: The fields of this FieldSnapshot.  # noqa: E501
        :type: dict(str, Object)
        """

        self._fields = fields

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FieldSnapshot, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FieldSnapshot):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
