# coding: utf-8

"""
    OnePlan API

    This is an automatically generated OpenAPI specification for the OnePlan API based on the api help docs.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RunwayResponseDep(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'to': 'GloballyUniqueIdentifier',
        'type': 'PlanDependencyStyle'
    }

    attribute_map = {
        'to': 'To',
        'type': 'Type'
    }

    def __init__(self, to=None, type=None):  # noqa: E501
        """RunwayResponseDep - a model defined in Swagger"""  # noqa: E501
        self._to = None
        self._type = None
        self.discriminator = None
        if to is not None:
            self.to = to
        if type is not None:
            self.type = type

    @property
    def to(self):
        """Gets the to of this RunwayResponseDep.  # noqa: E501


        :return: The to of this RunwayResponseDep.  # noqa: E501
        :rtype: GloballyUniqueIdentifier
        """
        return self._to

    @to.setter
    def to(self, to):
        """Sets the to of this RunwayResponseDep.


        :param to: The to of this RunwayResponseDep.  # noqa: E501
        :type: GloballyUniqueIdentifier
        """

        self._to = to

    @property
    def type(self):
        """Gets the type of this RunwayResponseDep.  # noqa: E501


        :return: The type of this RunwayResponseDep.  # noqa: E501
        :rtype: PlanDependencyStyle
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this RunwayResponseDep.


        :param type: The type of this RunwayResponseDep.  # noqa: E501
        :type: PlanDependencyStyle
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RunwayResponseDep, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RunwayResponseDep):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
