# coding: utf-8

"""
    OnePlan API

    This is an automatically generated OpenAPI specification for the OnePlan API based on the api help docs.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RunwayPost(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'plans': 'list[GloballyUniqueIdentifier]',
        'columns': 'list[RunwayPostCol]'
    }

    attribute_map = {
        'plans': 'Plans',
        'columns': 'Columns'
    }

    def __init__(self, plans=None, columns=None):  # noqa: E501
        """RunwayPost - a model defined in Swagger"""  # noqa: E501
        self._plans = None
        self._columns = None
        self.discriminator = None
        if plans is not None:
            self.plans = plans
        if columns is not None:
            self.columns = columns

    @property
    def plans(self):
        """Gets the plans of this RunwayPost.  # noqa: E501


        :return: The plans of this RunwayPost.  # noqa: E501
        :rtype: list[GloballyUniqueIdentifier]
        """
        return self._plans

    @plans.setter
    def plans(self, plans):
        """Sets the plans of this RunwayPost.


        :param plans: The plans of this RunwayPost.  # noqa: E501
        :type: list[GloballyUniqueIdentifier]
        """

        self._plans = plans

    @property
    def columns(self):
        """Gets the columns of this RunwayPost.  # noqa: E501


        :return: The columns of this RunwayPost.  # noqa: E501
        :rtype: list[RunwayPostCol]
        """
        return self._columns

    @columns.setter
    def columns(self, columns):
        """Sets the columns of this RunwayPost.


        :param columns: The columns of this RunwayPost.  # noqa: E501
        :type: list[RunwayPostCol]
        """

        self._columns = columns

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RunwayPost, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RunwayPost):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
