# coding: utf-8

"""
    OnePlan API

    This is an automatically generated OpenAPI specification for the OnePlan API based on the api help docs.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TableFilter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'condition': 'str',
        'id': 'str',
        'field': 'str',
        'operator': 'str',
        'value': 'str',
        'type': 'str'
    }

    attribute_map = {
        'condition': 'condition',
        'id': 'id',
        'field': 'field',
        'operator': 'operator',
        'value': 'value',
        'type': 'type'
    }

    def __init__(self, condition=None, id=None, field=None, operator=None, value=None, type=None):  # noqa: E501
        """TableFilter - a model defined in Swagger"""  # noqa: E501
        self._condition = None
        self._id = None
        self._field = None
        self._operator = None
        self._value = None
        self._type = None
        self.discriminator = None
        if condition is not None:
            self.condition = condition
        if id is not None:
            self.id = id
        if field is not None:
            self.field = field
        if operator is not None:
            self.operator = operator
        if value is not None:
            self.value = value
        if type is not None:
            self.type = type

    @property
    def condition(self):
        """Gets the condition of this TableFilter.  # noqa: E501


        :return: The condition of this TableFilter.  # noqa: E501
        :rtype: str
        """
        return self._condition

    @condition.setter
    def condition(self, condition):
        """Sets the condition of this TableFilter.


        :param condition: The condition of this TableFilter.  # noqa: E501
        :type: str
        """

        self._condition = condition

    @property
    def id(self):
        """Gets the id of this TableFilter.  # noqa: E501


        :return: The id of this TableFilter.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TableFilter.


        :param id: The id of this TableFilter.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def field(self):
        """Gets the field of this TableFilter.  # noqa: E501


        :return: The field of this TableFilter.  # noqa: E501
        :rtype: str
        """
        return self._field

    @field.setter
    def field(self, field):
        """Sets the field of this TableFilter.


        :param field: The field of this TableFilter.  # noqa: E501
        :type: str
        """

        self._field = field

    @property
    def operator(self):
        """Gets the operator of this TableFilter.  # noqa: E501


        :return: The operator of this TableFilter.  # noqa: E501
        :rtype: str
        """
        return self._operator

    @operator.setter
    def operator(self, operator):
        """Sets the operator of this TableFilter.


        :param operator: The operator of this TableFilter.  # noqa: E501
        :type: str
        """

        self._operator = operator

    @property
    def value(self):
        """Gets the value of this TableFilter.  # noqa: E501


        :return: The value of this TableFilter.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this TableFilter.


        :param value: The value of this TableFilter.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def type(self):
        """Gets the type of this TableFilter.  # noqa: E501


        :return: The type of this TableFilter.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this TableFilter.


        :param type: The type of this TableFilter.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TableFilter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TableFilter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
