# coding: utf-8

"""
    OnePlan API

    This is an automatically generated OpenAPI specification for the OnePlan API based on the api help docs.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TeamAllocationRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'resource_id': 'GloballyUniqueIdentifier',
        'zoom_level': 'Zoom',
        'values': 'dict(str, DecimalNumber)'
    }

    attribute_map = {
        'resource_id': 'ResourceId',
        'zoom_level': 'ZoomLevel',
        'values': 'Values'
    }

    def __init__(self, resource_id=None, zoom_level=None, values=None):  # noqa: E501
        """TeamAllocationRequest - a model defined in Swagger"""  # noqa: E501
        self._resource_id = None
        self._zoom_level = None
        self._values = None
        self.discriminator = None
        if resource_id is not None:
            self.resource_id = resource_id
        if zoom_level is not None:
            self.zoom_level = zoom_level
        if values is not None:
            self.values = values

    @property
    def resource_id(self):
        """Gets the resource_id of this TeamAllocationRequest.  # noqa: E501


        :return: The resource_id of this TeamAllocationRequest.  # noqa: E501
        :rtype: GloballyUniqueIdentifier
        """
        return self._resource_id

    @resource_id.setter
    def resource_id(self, resource_id):
        """Sets the resource_id of this TeamAllocationRequest.


        :param resource_id: The resource_id of this TeamAllocationRequest.  # noqa: E501
        :type: GloballyUniqueIdentifier
        """

        self._resource_id = resource_id

    @property
    def zoom_level(self):
        """Gets the zoom_level of this TeamAllocationRequest.  # noqa: E501


        :return: The zoom_level of this TeamAllocationRequest.  # noqa: E501
        :rtype: Zoom
        """
        return self._zoom_level

    @zoom_level.setter
    def zoom_level(self, zoom_level):
        """Sets the zoom_level of this TeamAllocationRequest.


        :param zoom_level: The zoom_level of this TeamAllocationRequest.  # noqa: E501
        :type: Zoom
        """

        self._zoom_level = zoom_level

    @property
    def values(self):
        """Gets the values of this TeamAllocationRequest.  # noqa: E501


        :return: The values of this TeamAllocationRequest.  # noqa: E501
        :rtype: dict(str, DecimalNumber)
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this TeamAllocationRequest.


        :param values: The values of this TeamAllocationRequest.  # noqa: E501
        :type: dict(str, DecimalNumber)
        """

        self._values = values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TeamAllocationRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TeamAllocationRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
