export default {
  notes: "mdi-comment-outline",
  description: "mdi-comment-outline",
  inventory: "mdi-folder-home-outline",
  categories: "mdi-label-multiple-outline",
  category: "mdi-label-outline",
  manufacturer: "mdi-factory",
  locations: "mdi-map-marker-multiple-outline",
  location: "mdi-map-marker-outline",
  item: "mdi-inbox-outline",
  items: "mdi-inbox-multiple-outline",
  partNumber: "mdi-counter",
  serialNumber: "mdi-counter",
  itemType: "mdi-shape-outline",
  itemTypes: "mdi-shape-outline",
  status: "mdi-map-marker-question-outline",
  barcode: "mdi-barcode",
  lastTimeSeenAt: "mdi-clock-check-outline",
  checkOut: "mdi-cart-arrow-down",
  checkIn: "mdi-cart-arrow-up",
  person: "mdi-account-outline",
  checkOutCondition: "mdi-regex",
  date: "mdi-calendar-outline",
  checkedOutAt: "mdi-clock-outline",
  containedIn: "mdi-archive-outline",
};
