from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.ABB_IRB_910SC_3 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.ABB_IRB_920T_6_055 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.ABB_IRB_920T_6_065 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Adept_Cobra_s350 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Adept_Cobra_s600 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Adept_Cobra_s800 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Adept_Cobra_s800_inverted import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Brooks_PreciseFlex_400_400 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Brooks_PreciseFlex_400_750 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Brooks_PreciseFlex_400_1160 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Brooks_PreciseFlex_3400_400 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Brooks_PreciseFlex_3400_750 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Brooks_PreciseFlex_3400_1160 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Brooks_PreciseFlex_DD4axis_500 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Brooks_PreciseFlex_DD4axis_1000 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Brooks_PreciseFlex_DD4axis_1420 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Comau_Rebel_S6_045 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Comau_Rebel_S6_060 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Comau_Rebel_S6_075 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Denso_HM_4A73 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Denso_HSR065A1_N17_W5N import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Dobot_M1 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Epson_G1_221S import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Epson_G1_171S import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Epson_G6_651S import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Epson_G6_653S import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Epson_GX8_A552C import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Epson_LS3_401S import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Epson_LS6_502S import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Epson_LS6_602S import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Epson_LS20_B804S import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Epson_LS20_BA04S import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Epson_RS3 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Epson_RS4 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Epson_T3_401S import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Epson_T6_602S import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Fanuc_SR_3iA import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Fanuc_SR_6iA import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Fanuc_SR_12iA import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Fanuc_SR_20iA import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.IAI_IXA_4NNN3015 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.IAI_IAX_4NNN4518 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.IAI_IXA_4NNN6018 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Kawasaki_duAro_1A import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Kawasaki_duAro_1B import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.KUKA_KR5_scara_R350_Z200 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.KUKA_KR5_scara_R350_Z320 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.KUKA_KR5_scara_R550_Z200 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.KUKA_KR5_scara_R550_Z320 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.KUKA_KR6_R700_Z200 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.KUKA_KR10_scara_R600_Z300 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.KUKA_KR10_scara_R600_Z400 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.KUKA_KR10_scara_R850_Z300 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.KUKA_KR10_scara_R850_Z400 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Leantec_LS400_3_Y import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Leantec_LS600_6_Y import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Leantec_LS900_10_Y import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.MCI_SR4_6_550 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Mecademic_MCS500 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.MIP_Junior_300 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Mitsubishi_RH_3CH import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Mitsubishi_RH_3FRH3515 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Mitsubishi_RH_3FRH4515 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Mitsubishi_RH_3FRH5515 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Mitsubishi_RH_6CH60 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Mitsubishi_RH_6CH70 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Mitsubishi_RH_12FH7035 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Mitsubishi_RH_12SH5535 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Mitsubishi_RH_20FRH_8535 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Motoman_MYS650L import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Motoman_MYS850L import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Motoman_MYS1000 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Nachi_EZ03V4_02_4525 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Omron_i4_350L import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Omron_i4_450L import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Omron_i4_550L import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Omron_i4_650H import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Omron_i4_750H import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Omron_i4_850H import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.RoboDK_RDK_SCARA_70 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Rokae_RS3_4515 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Rokae_RS3_5515 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Shibaura_Machine_THE400 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Shibaura_Machine_THE400T import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Shibaura_Machine_THE600 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Shibaura_Machine_THE600T import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Shibaura_Machine_THE800 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Shibaura_Machine_THE1000 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Shibaura_Machine_THL400 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Shibaura_Machine_THL600 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Shibaura_Machine_THL700 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Shibaura_Machine_THL700_Ceiling import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Shibaura_Machine_THL800 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Shibaura_Machine_THL800_Ceiling import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Shibaura_Machine_THL1200 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Staubli_TP80 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Staubli_TS2_40FL200 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Staubli_TS2_60FL200 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Staubli_TS2_80FL200 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Staubli_TS2_100FL200 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Staubli_TS2_100HBFL400L_WS_FLA import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Staubli_TS20_FL100TC import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Staubli_TS40_FL200 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Staubli_TS60_FL400 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Staubli_TS80_FL400 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Yamaha_YK400XR_S150 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Yamaha_YK700XGP_200 import *
from robotkinematicscatalogue.inversekinematics.__4DOF.__SCARA.Yamaha_YK800XGP_200 import *