# Generated by Django 3.2.15 on 2022-10-13 15:31

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plank', '0004_colour_icon_perms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='colour',
            field=colorfield.fields.ColorField(default='#00000000', image_field=None, max_length=18, samples=None, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plank.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_types', to='plank.category', verbose_name='Category'),
        ),
    ]
