# Generated by Django 3.2.15 on 2022-10-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plank', '0007_perms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['name'], 'permissions': [('view_category_for_inventory', 'Can view category for inventory'), ('change_category_for_inventory', 'Can change category for inventory'), ('delete_category_for_inventory', 'Can delete category for inventory'), ('create_category_for_inventory', 'Can create category for inventory'), ('view_manufacturer_for_inventory', 'Can view manufacturer for inventory'), ('change_manufacturer_for_inventory', 'Can change manufacturer for inventory'), ('delete_manufacturer_for_inventory', 'Can delete manufacturer for inventory'), ('create_manufacturer_for_inventory', 'Can create manufacturer for inventory'), ('view_site_for_inventory', 'Can view site for inventory'), ('change_site_for_inventory', 'Can change site for inventory'), ('delete_site_for_inventory', 'Can delete site for inventory'), ('create_site_for_inventory', 'Can create site for inventory'), ('view_room_for_inventory', 'Can view room for inventory'), ('change_room_for_inventory', 'Can change room for inventory'), ('delete_room_for_inventory', 'Can delete room for inventory'), ('create_room_for_inventory', 'Can create room for inventory'), ('view_location_for_inventory', 'Can view location for inventory'), ('change_location_for_inventory', 'Can change location for inventory'), ('delete_location_for_inventory', 'Can delete location for inventory'), ('create_location_for_inventory', 'Can create location for inventory')], 'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventories'},
        ),
    ]
