# Generated by Django 3.2.16 on 2022-12-10 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plank', '0012_only_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutprocess',
            old_name='lending_user',
            new_name='lending_person',
        ),
    ]
