#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2404-59-g79d385dc"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2404
#define NETGEN_VERSION_TWEAK 59
#define NETGEN_VERSION_HASH "g79d385dc"
#endif // NETGEN_VERSION_HPP_INCLUDED
