import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_217b348c32(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_5b4649203d():spartaqube_cli.list()
@app.command()
def sparta_58511a9866():spartaqube_cli.sparta_58511a9866()
@app.command()
def sparta_83773118fb():print('Hello world!')
if __name__=='__main__':app()