import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_1b9e703566(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_c421ab6441():spartaqube_cli.list()
@app.command()
def sparta_b3714494fe():spartaqube_cli.sparta_b3714494fe()
@app.command()
def sparta_14ead057f0():print('Hello world!')
if __name__=='__main__':app()