# Generated by Django 3.1.5 on 2021-01-21 10:54

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210111_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderform',
            name='sender',
            field=models.TextField(blank=True, verbose_name='Sender'),
        ),
    ]
