
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-28T09:38:22+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e9bcd51b97d16ee7c3ff7a7523edc871d86ee44c",
 "version": "5.7.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
