# Autogenerated by nbdev

d = { 'settings': { 'branch': '_ghpages',
                'doc_baseurl': '/https://github.com/44moles/obsidian2quarto',
                'doc_host': 'https://mone27.github.io',
                'git_url': 'https://github.com/mone27/https://github.com/44moles/obsidian2quarto',
                'lib_path': 'obsidian2quarto'},
  'syms': { 'obsidian2quarto.core': { 'obsidian2quarto.core.convert_images': ( 'obsidian2quarto.html#convert_images',
                                                                               'obsidian2quarto/core.py'),
                                      'obsidian2quarto.core.convert_md': ('obsidian2quarto.html#convert_md', 'obsidian2quarto/core.py'),
                                      'obsidian2quarto.core.convert_vault': ( 'obsidian2quarto.html#convert_vault',
                                                                              'obsidian2quarto/core.py'),
                                      'obsidian2quarto.core.copy_vault': ('obsidian2quarto.html#copy_vault', 'obsidian2quarto/core.py'),
                                      'obsidian2quarto.core.ignore_names_copy': ( 'obsidian2quarto.html#ignore_names_copy',
                                                                                  'obsidian2quarto/core.py'),
                                      'obsidian2quarto.core.obsidian2quarto': ( 'obsidian2quarto.html#obsidian2quarto',
                                                                                'obsidian2quarto/core.py'),
                                      'obsidian2quarto.core.read_config': ('obsidian2quarto.html#read_config', 'obsidian2quarto/core.py')}}}
