# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic

from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..common.application_info import ApplicationInfo
from ..common.role_info import RoleInfo
from ..common.user_info import UserInfo
from .group_type import GroupType


class Group(UniversalBaseModel):
    uid: str
    name: str
    type: GroupType
    description: typing.Optional[str] = None
    created: dt.datetime
    applications: typing.Optional[typing.List[ApplicationInfo]] = None
    roles: typing.Optional[typing.List[RoleInfo]] = None
    users: typing.Optional[typing.List[UserInfo]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            extra = pydantic.Extra.allow
