# Copyright 2022 OpenSynergy Indonesia
# Copyright 2022 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "Commission Management",
    "version": "14.0.1.4.0",
    "website": "https://simetri-sinergi.id",
    "author": "OpenSynergy Indonesia, PT. Simetri Sinergi Indonesia",
    "license": "AGPL-3",
    "installable": True,
    "application": True,
    "depends": [
        "ssi_master_data_mixin",
        "ssi_transaction_confirm_mixin",
        "ssi_transaction_done_mixin",
        "ssi_transaction_cancel_mixin",
        "ssi_transaction_open_mixin",
        "ssi_transaction_partner_mixin",
        "ssi_localdict_mixin",
        "ssi_account_account_m2o_configurator_mixin",
        "ssi_account_journal_m2o_configurator_mixin",
        "ssi_res_partner_m2o_configurator_mixin",
        "ssi_res_currency_m2o_configurator_mixin",
        "ssi_res_partner_bank_m2o_configurator_mixin",
        "ssi_res_users_m2o_configurator_mixin",
        "ssi_m2o_configurator_mixin",
        "ssi_transaction_date_due_mixin",
        "ssi_transaction_date_duration_mixin",
        "ssi_accounting_entry_mixin",
        "ssi_company_currency_mixin",
        "ssi_currency_mixin",
        "ssi_product_line_account_mixin",
        "ssi_transaction_total_mixin",
        "base_automation",
        "partner_contact_in_several_companies",
        "sales_team",
    ],
    "data": [
        "security/ir_module_category_data.xml",
        "security/res_group_data.xml",
        "security/ir.model.access.csv",
        "security/ir_rule_data.xml",
        "data/ir_sequence_data.xml",
        "data/sequence_template_data.xml",
        "data/approval_template_data.xml",
        "data/policy_template_data.xml",
        "data/ir_actions_server_data.xml",
        "data/base_automation_data.xml",
        "menu.xml",
        "views/commission_type_views.xml",
        "views/commission_item_views.xml",
        "views/commission_views.xml",
        "views/marketing_commission_item_views.xml",
        "views/marketing_commission_type_views.xml",
        "views/marketing_commission_views.xml",
    ],
    "demo": [],
}
