# Generated by Django 3.2.12 on 2022-03-10 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kort', '0004_alter_card_chip_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='cards/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='PDF file'),
        ),
    ]
