# Generated by Django 3.2.12 on 2022-03-26 20:23

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kort', '0009_cardprinter_generate_number_on_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardprintjob',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='cardprintjob',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
