# Generated by Django 4.2.4 on 2023-08-30 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kort", "0015_migrate_scopes"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardprinter",
            name="oauth2_client_secret",
            field=models.CharField(blank=True, max_length=255, verbose_name="OAuth2 client secret"),
        ),
    ]
