# Generated by Django 4.2.10 on 2024-02-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kort', '0016_cardprinter_oauth2_client_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='managed_by_app_label',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='App label of app responsible for managing this instance'),
        ),
        migrations.AddField(
            model_name='cardlayout',
            name='managed_by_app_label',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='App label of app responsible for managing this instance'),
        ),
        migrations.AddField(
            model_name='cardlayoutmediafile',
            name='managed_by_app_label',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='App label of app responsible for managing this instance'),
        ),
        migrations.AddField(
            model_name='cardprinter',
            name='managed_by_app_label',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='App label of app responsible for managing this instance'),
        ),
        migrations.AddField(
            model_name='cardprintjob',
            name='managed_by_app_label',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='App label of app responsible for managing this instance'),
        ),
        migrations.AlterField(
            model_name='cardprinter',
            name='cups_printer',
            field=models.CharField(blank=True, help_text='Leave blank to deactivate CUPS printing', max_length=255, verbose_name='CUPS printer'),
        ),
    ] + [
        migrations.RunSQL(
            f"ALTER TABLE kort_{model_name} drop column if exists site_id;"
        ) for model_name  in
        [
            "cardprinter",
            "cardlayoutmediafile",
            "cardlayout",
            "card",
            "cardprintjob",
        ]
    ]

