
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-01T21:38:51+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "339243a47eb3fa98faaffb89e3ec3f27c25e7ea5",
 "version": "0.0.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
