
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-30T13:34:45+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8f46d7fb2d351e2aa7bb9bdf5dc8e33d2edf05a6",
 "version": "0.0.56.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
