
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-29T09:38:44+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f9554786e9d7f81c0195e0d9ab3c22b7fe611799",
 "version": "8.19.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
