
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-28T16:30:43-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "7f57c43baae3a1c1fd125141d1f182ed51c745b5",
 "version": "2.44.0rc0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
