import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_69bcf9abac(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_494c7d0d61():spartaqube_cli.list()
@app.command()
def sparta_6d74ffc561():spartaqube_cli.sparta_6d74ffc561()
@app.command()
def sparta_ee5a4ea394():print('Hello world!')
if __name__=='__main__':app()