
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-02T21:47:40+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "6ce922114b89e597c23442b0ca84c66273572f4f",
 "version": "0.44"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
