# coding: utf-8

"""
    Dokumenty CITES

    API pro datový řadič dokumentů CITES ### Verze 1.0.0    - public   - developers  ### Verze 1.1.0    - admins   - additional   - statement   - attachments   - registration_cards   - permit   # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: info@sysnet.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import citesdoc_110
from citesdoc_110.models.transport_event_type import TransportEventType  # noqa: E501
from citesdoc_110.rest import ApiException


class TestTransportEventType(unittest.TestCase):
    """TransportEventType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransportEventType(self):
        """Test TransportEventType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = citesdoc_110.models.transport_event_type.TransportEventType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
