import os

#ENV CONSTANTS
CODE_URL = "CODE_URL"
LOCAL_CODE_PATH = "LOCAL_CODE_PATH"

DATASET_URL = "DATASET_URL"
LOCAL_DATASET_PATH = "LOCAL_DATASET_PATH"

PRETRAIN_MODEL_URL = "PRETRAIN_MODEL_URL"
LOCAL_PRETRAIN_MODEL_PATH = "LOCAL_PRETRAIN_MODEL_PATH"

OUTPUT_URL = "OUTPUT_URL"
LOCAL_OUTPUT_PATH = "LOCAL_OUTPUT_PATH"

LOCAL_TENSORBOARD_PATH = "LOCAL_TENSORBOARD_PATH"

DATA_DOWNLOAD_METHOD = "DATA_DOWNLOAD_METHOD"
DATA_DOWNLOAD_METHOD_MOUNT= "MOUNT"
DATA_DOWNLOAD_METHOD_MOXING= "MOXING"

CODE_NEED_UNZIP = "CODE_NEED_UNZIP"
CODE_NEED_UNZIP_TRUE = "true"
CODE_NEED_UNZIP_FALSE = "false"

DATASET_NEED_UNZIP = "DATASET_NEED_UNZIP"
DATASET_NEED_UNZIP_TRUE = "true"
DATASET_NEED_UNZIP_FALSE = "false"

PRETRAIN_MODEL_NEED_UNZIP = "PRETRAIN_MODEL_NEED_UNZIP"
PRETRAIN_MODEL_NEED_UNZIP_TRUE = "true"
PRETRAIN_MODEL_NEED_UNZIP_FALSE = "false"


