PARTBZ = {
    5000: "Zone à bâtir",
    5001: "Bâtiments d'exploitation pour agriculture tributaire du sol",
    5002: "Constructions agricoles pour préparation, stockage et vente",
    5003: "Bâtiments d'habitation pour une entreprise agricole",
    5004: "Constructions pour garde en commun d'animaux de rente",
    5005: "Développement interne pour la garde d'animaux (halles pour porcs ou volaille)",
    5006: "Développement interne pour la culture de légumes et autres végétaux (serres)",
    5007: "Constructions conformes à une zone agricole spéciale",
    5008: "Production d'énergie à partir de biomasse",
    5009: "Constructions et installations conformes dans des zones de protection",
    5011: "Constructions et installations conformes en zones spéciales (décharge, sport etc., à l'exception des hameaux et des zones de maintien de l'habitat rural)",
    5012: "Constructions conformes à une zone de hameau ou les zones de maintien de l'habitat rural etc.",
    5015: "Installations solaires",
    5021: "Constructions imposées par leur destination",
    5022: "Changement complet d'affectation, territoire à habitat dispersé",
    5023: "Changement complet d'affectation de constructions protégées en tant qu'éléments caractéristiques du paysage",
    5031: "Changement d'affectation sans travaux de transformation",
    5041: "Act. non agr. nécessaire à la survie de l'exploitation",
    5043: "Act. non agr. étroitement liées à l'exploitation agricol",
    5044: "Act. non agr. dans centres d'exploitation temporaires",
    5051: "Modification de constructions devenues contraires à la zone",
    5061: "Transformation d'anciens logements agricoles",
    5062: "Changement complet d'affectation de constructions protégées",
    5063: "Détention d'animaux de loisir dans bâtiments proches",
    5064: "Installations extérieures pour détention d'animaux de loisir",
    5071: "Modification de constructions à usage commercial devenues contraires à la zone",
}
