PTYPBW = {
    6211: "Installations pour l'alimentation en eau",
    6212: "Usines d'électricité et réseaux",
    6213: "Usines à gaz, réseaux et installations chimiques",
    6214: "Installations de chauffage à distance",
    6219: "Autres installations d'approvisionnement",
    6221: "Installations d'évacuation et de traitement des eaux usées",
    6222: "Installations de traitement des ordures ménagères",
    6223: "Installations de traitement des autres déchets",
    6231: "Routes nationales",
    6232: "Routes cantonales",
    6233: "Routes communales",
    6234: "Autres constructions routières, places de stationnement",
    6235: "Parkings couverts",
    6241: "Constructions pour les chemins de fer",
    6242: "Constructions pour les bus et tramways",
    6243: "Constructions pour la navigation",
    6244: "Constructions pour les transports aériens",
    6245: "Constructions pour les communications",
    6249: "Autres constructions vouées aux transports",
    6251: "Ecoles, systèmes d'éducation jusqu'au niveau de la maturité",
    6252: "Etablissements de formation supérieure et de recherche",
    6253: "Hôpitaux d'urgence, hôpitaux généraux",
    6254: "Foyers avec soins médicaux et/ou services d'assistance sociale",
    6255: "Autres établissements de santé spécialisés",
    6256: "Installations de loisirs et de tourisme",
    6257: "Eglises et bâtiments à but religieux",
    6258: "Bâtiments à but culturel incl. musées, bibliothèques et monuments",
    6259: "Salles omnisports et places de sport",
    6261: "Aménagements de berges et barrages",
    6262: "Constructions pour la défense nationale",
    6269: "Autres infrastructures",
    6271: "Maisons individuelles isolées",
    6272: "Maisons individuelles mitoyennes",
    6273: "Maisons à plusieurs logements (à usage exclusif d'habitation)",
    6274: "Bâtiments à usage annexe (y compris ruraux)",
    6276: "Foyers sans soins médicaux et/ou services d'assistance sociale",
    6278: "Garages, places de parc en rapport avec l'habitation",
    6279: "Autres constructions en rapport avec l'habitation",
    6281: "Constructions agricoles",
    6282: "Constructions sylvicoles",
    6283: "Améliorations foncières",
    6291: "Fabriques, usines, ateliers",
    6292: "Halles, dépôts, silos, citernes",
    6293: "Bâtiments administratifs, bureaux",
    6294: "Bâtiments commerciaux, magasins",
    6295: "Hôtels, restaurants",
    6296: "Autres hébergements de courte durée",
    6299: "Autres constructions destinées à des activités économiques",
}
