import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_29e74c4cfb(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_6f8137ddc8():spartaqube_cli.list()
@app.command()
def sparta_23fd3e8989():spartaqube_cli.sparta_23fd3e8989()
@app.command()
def sparta_7cb9a42e6a():print('Hello world!')
if __name__=='__main__':app()