# Generated by Django 3.2.16 on 2022-12-05 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('plank', '0010_perms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckOutItem',
            new_name='CheckedOutItem',
        ),
        migrations.AlterModelOptions(
            name='checkoutprocess',
            options={'ordering': ['-check_in_until', '-checked_out_at'],
                     'permissions': [('check_out', 'Can check out items'), ('check_in', 'Can check in items')],
                     'verbose_name': 'Check out process', 'verbose_name_plural': 'Check out processes'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['name'],
                     'permissions': [('view_category_for_inventory', 'Can view category for inventory'),
                                     ('change_category_for_inventory', 'Can change category for inventory'),
                                     ('delete_category_for_inventory', 'Can delete category for inventory'),
                                     ('create_category_for_inventory', 'Can create category for inventory'),
                                     ('view_manufacturer_for_inventory', 'Can view manufacturer for inventory'),
                                     ('change_manufacturer_for_inventory', 'Can change manufacturer for inventory'),
                                     ('delete_manufacturer_for_inventory', 'Can delete manufacturer for inventory'),
                                     ('create_manufacturer_for_inventory', 'Can create manufacturer for inventory'),
                                     ('view_site_for_inventory', 'Can view site for inventory'),
                                     ('change_site_for_inventory', 'Can change site for inventory'),
                                     ('delete_site_for_inventory', 'Can delete site for inventory'),
                                     ('create_site_for_inventory', 'Can create site for inventory'),
                                     ('view_room_for_inventory', 'Can view room for inventory'),
                                     ('change_room_for_inventory', 'Can change room for inventory'),
                                     ('delete_room_for_inventory', 'Can delete room for inventory'),
                                     ('create_room_for_inventory', 'Can create room for inventory'),
                                     ('view_location_for_inventory', 'Can view location for inventory'),
                                     ('change_location_for_inventory', 'Can change location for inventory'),
                                     ('delete_location_for_inventory', 'Can delete location for inventory'),
                                     ('create_location_for_inventory', 'Can create location for inventory'),
                                     ('view_itemtype_for_inventory', 'Can view item type for inventory'),
                                     ('change_itemtype_for_inventory', 'Can change item type for inventory'),
                                     ('delete_itemtype_for_inventory', 'Can delete item type for inventory'),
                                     ('create_itemtype_for_inventory', 'Can create item type for inventory'),
                                     ('view_item_for_inventory', 'Can view item for inventory'),
                                     ('change_item_for_inventory', 'Can change item for inventory'),
                                     ('delete_item_for_inventory', 'Can delete item for inventory'),
                                     ('create_item_for_inventory', 'Can create item for inventory'),
                                     ('check_out_for_inventory', 'Can check out items for inventory'),
                                     ('check_in_for_inventory', 'Can check out items for inventory')],
                     'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories',
                                    to='plank.inventory'),
        ),
        migrations.AlterField(
            model_name='checkedoutitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked_out_items',
                                    to='plank.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='checkedoutitem',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked_out_items',
                                    to='plank.checkoutprocess', verbose_name='Check out process'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='check_out_groups',
            field=models.ManyToManyField(blank=True, help_text='To persons in this groups things can be checked out.',
                                         null=True, related_name='_plank_inventory_check_out_groups_+', to='core.Group',
                                         verbose_name='Groups with check out permission'),
        ),
    ]
