# Generated by Django 3.2.16 on 2022-12-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plank', '0014_alter_item_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['name'], 'permissions': [('view_category_for_inventory', 'Can view category for inventory'), ('change_category_for_inventory', 'Can change category for inventory'), ('delete_category_for_inventory', 'Can delete category for inventory'), ('create_category_for_inventory', 'Can create category for inventory'), ('view_manufacturer_for_inventory', 'Can view manufacturer for inventory'), ('change_manufacturer_for_inventory', 'Can change manufacturer for inventory'), ('delete_manufacturer_for_inventory', 'Can delete manufacturer for inventory'), ('create_manufacturer_for_inventory', 'Can create manufacturer for inventory'), ('view_location_for_inventory', 'Can view location for inventory'), ('change_location_for_inventory', 'Can change location for inventory'), ('delete_location_for_inventory', 'Can delete location for inventory'), ('create_location_for_inventory', 'Can create location for inventory'), ('view_itemtype_for_inventory', 'Can view item type for inventory'), ('change_itemtype_for_inventory', 'Can change item type for inventory'), ('delete_itemtype_for_inventory', 'Can delete item type for inventory'), ('create_itemtype_for_inventory', 'Can create item type for inventory'), ('view_item_for_inventory', 'Can view item for inventory'), ('change_item_for_inventory', 'Can change item for inventory'), ('delete_item_for_inventory', 'Can delete item for inventory'), ('create_item_for_inventory', 'Can create item for inventory'), ('check_out_for_inventory', 'Can check out items for inventory'), ('check_in_for_inventory', 'Can check out items for inventory'), ('view_checkoutprocess_for_inventory', 'Can view check out process for inventory'), ('change_checkoutprocess_for_inventory', 'Can change check out process for inventory')], 'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventories'},
        ),
    ]
