# Generated by Django 4.2.11 on 2024-05-05 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plank', '0018_item_contained_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_location', to='plank.item', verbose_name='Item'),
        ),
    ]
